nginxReplicaCount: 1

phpReplicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  nginx:
    name: crater-nginx
    tag: latest
  php:
    name: crater-php
    tag: latest

service:
  nginx:
    type: ClusterIP
    port: 80
  php:
    type: ClusterIP
    port: 9000

config:
  APP_URL: http://crater.test
  DB_DATABASE: crater
  DB_HOST: craterdb
  DB_PORT: 3306
  SANCTUM_STATEFUL_DOMAINS: crater.test
  SESSION_DOMAIN: crater.test
  AUTO_INSTALL: "true"
  ADMIN_NAME: Jane Doe
  COMPANY_NAME: xyz
  COMPANY_SLUG: xyz
  COUNTRY_ID: 1

secrets:
  DB_USERNAME: ""
  DB_PASSWORD: ""
  ADMIN_EMAIL: ""
  ADMIN_PASSWORD: ""

autoscaling:
  enabled: false
