version: '3'

services:
  app:
    image: craterapp/crater-php
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - crater

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      #- ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

  nginx:
    image: craterapp/crater-nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - crater

  cron:
    build:
      context: ../
      dockerfile: docker/cron.dockerfile
    image: crater-cron
    volumes:
      - ../:/var/www
    networks:
      - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
