apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  DB_HOST:  {{ .Values.secrets.DB_HOST | b64enc | quote }}
  DB_PORT:  {{ .Values.secrets.DB_PORT | b64enc | quote }}
  DB_USERNAME:  {{ .Values.secrets.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD:  {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  ADMIN_EMAIL:  {{ .Values.secrets.ADMIN_EMAIL | b64enc | quote }}
  ADMIN_PASSWORD:  {{ .Values.secrets.ADMIN_PASSWORD | b64enc | quote }}
