name: CI

on:
  push:
    branches:
      - bahmni-master
    tags:
      - "*"
  pull_request:
    branches:
      - bahmni-master
env:
  CRATER_VERSION: 1.0.0
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: exif

    - name: Install PHP 7 dependencies
      run: composer update --no-interaction --no-progress
      if: "matrix.php < 8"

    - name: Install PHP 8 dependencies
      run: composer update --ignore-platform-req=php --no-interaction --no-progress
      if: "matrix.php >= 8"

    - name: Check coding style
      run: ./vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no --config=.php-cs-fixer.dist.php

    - name: Unit Tests
      run: php ./vendor/bin/pest

  docker:
    if: ${{ needs.build-test.result == 'success' && github.event_name != 'pull_request'}}
# env is not avaialble in context of evaluating condition or building another env. workaround was to use seperate steps to construct VERSION_TAG env variable
    # env:
        # VERSION_TAG: ${{ startsWith(github.ref, 'refs/tags/v') && env.CRATER_VERSION || env.CRATER_VERSION-github.run_number }}
    name: Docker build and publish
    runs-on: ubuntu-latest
    needs:
      - build-test
    env:
      HELM_CHART_PATH: package/helm/crater
    steps:
    - name: check if prod release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "VERSION_TAG=${{ env.CRATER_VERSION }}"
        echo "VERSION_TAG=${{ env.CRATER_VERSION }}" >> $GITHUB_ENV
    - name: check if dev release
      if: startsWith(github.ref, 'refs/tags/v') != true
      run: |
        echo "VERSION_TAG=${{ env.CRATER_VERSION }}-${{ github.run_number }}"
        echo "VERSION_TAG=${{ env.CRATER_VERSION }}-${{ github.run_number }}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Docker Build and push crater-php
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        push: true
        # :product is just a temp tag - eventually the crater-image would come from the craterapp dockerhub repo
        # PR https://github.com/crater-invoice/crater/pull/922
        tags: bahmni/crater-php:product
    - name: Docker Build and push crater-nginx
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/nginx.Dockerfile
        push: true
        tags: bahmni/crater-nginx:${{env.VERSION_TAG}},bahmni/crater-nginx:latest
